// ---------------------------------------------------------------------------
// Everything the page knows about the four houses, gathered 2026-09-21.
//
// Listing facts come from each realtor.com listing (the MLS data behind it).
// Wildfire figures come from the USDA Forest Service "Wildfire Risk to
// Communities" rasters (2024 release), sampled on a 7x7 grid at 60 m spacing
// around each house, so one developed pixel can't make a house look safe.
// Nearest grocery / gas / restaurant come from OpenStreetMap, ranked by
// driving distance (OSRM), not straight-line distance.
//
// Deliberately absent: the Chandler start address. Only drive times from it
// are stored, never its location.
// ---------------------------------------------------------------------------

export const TRIP = {
  sat: '2026-09-26',
  sun: '2026-09-27',
  sunset: '6:25 PM',
};

export const PLACES = {
  hotel:   { name: 'SpringHill Suites Prescott', addr: '200 E Sheldon St, Prescott, AZ 86301', lat: 34.5460353, lon: -112.4666382 },
  whiskey: { name: 'Whiskey Row', addr: 'S Montezuma St, Prescott, AZ', lat: 34.5409451, lon: -112.4705907 },
};

// Drive legs [miles, minutes] from OSRM. "home" = Chandler start (location withheld).
export const LEGS = {
  home:     { hotel: [127.2, 155], quintero: [129.2, 152], lavalley: [129.1, 160], pyrite: [132.9, 170], idylwild: [128.7, 158], banning: [130.0, 164], quartz: [133.0, 170], ponderosa: [133.3, 171] },
  hotel:    { home: [127.3, 157], whiskey: [0.7, 3], quintero: [8.9, 17], lavalley: [2.2, 7], pyrite: [6.2, 17], idylwild: [1.9, 5], banning: [2.8, 9], quartz: [5.8, 16], ponderosa: [6.1, 17] },
  whiskey:  { hotel: [0.6, 3], quintero: [8.7, 17], lavalley: [1.8, 6], pyrite: [5.7, 16], idylwild: [1.4, 3], banning: [2.3, 7], quartz: [5.3, 14], ponderosa: [5.6, 15] },
  quintero: { home: [129.4, 154], hotel: [8.9, 17], whiskey: [8.8, 18], lavalley: [9.8, 21], pyrite: [14.0, 31], idylwild: [8.7, 18], banning: [10.6, 22], quartz: [13.7, 29], ponderosa: [13.9, 30] },
  lavalley: { home: [129.2, 162], hotel: [2.2, 7], whiskey: [1.8, 6], quintero: [9.8, 21], pyrite: [4.6, 12], idylwild: [2.4, 7], banning: [1.2, 4], quartz: [4.2, 11], ponderosa: [4.5, 12] },
  pyrite:   { home: [133.1, 171], hotel: [6.2, 17], whiskey: [5.7, 15], quintero: [14.0, 31], lavalley: [4.6, 12], idylwild: [6.6, 17], banning: [4.0, 11], quartz: [0.4, 1], ponderosa: [0.2, 1] },
  idylwild: { home: [128.9, 159], hotel: [1.9, 5], whiskey: [1.6, 4], quintero: [8.8, 18], lavalley: [2.4, 7], pyrite: [6.6, 17], banning: [3.3, 8], quartz: [6.3, 15], ponderosa: [6.5, 16] },
  banning: { home: [130.0, 164], hotel: [2.8, 9], whiskey: [2.3, 7], quintero: [10.6, 22], lavalley: [1.2, 4], pyrite: [4.0, 11], idylwild: [3.3, 8], quartz: [3.7, 10], ponderosa: [3.9, 11] },
  quartz: { home: [133.0, 170], hotel: [5.8, 16], whiskey: [5.3, 14], quintero: [13.7, 29], lavalley: [4.2, 11], pyrite: [0.4, 1], idylwild: [6.3, 15], banning: [3.7, 10], ponderosa: [0.3, 1] },
  ponderosa: { home: [133.3, 171], hotel: [6.1, 17], whiskey: [5.6, 15], quintero: [13.9, 30], lavalley: [4.5, 12], pyrite: [0.2, 1], idylwild: [6.5, 16], banning: [3.9, 11], quartz: [0.3, 1] },
};

// Pyrite went under contract 2026-09-23, so it's off the route but still on the page.
// The three agent-collection houses added 2026-09-26 are all on Saturday; `defaultDay: 'sun'` on a house would default it to Sunday.
export const RECOMMENDED = ['quintero', 'idylwild', 'banning', 'lavalley', 'quartz', 'ponderosa'];

// The agent's flexmls collection of the three added houses (MLS sheets, no login needed).
const LIST_URL = 'https://www.flexmls.com/link.html?1zd6jq9y4g1o,12,1,44074';

const px = (base, ids) => ids.map(id => `https://${base}${id}od-w1024_h768.jpg`);

export const HOUSES = [
  {
    id: 'quintero',
    short: 'Quintero',
    addr: '1239 Quintero Rd',
    city: 'Prescott, AZ 86305',
    lat: 34.642524, lon: -112.444392,
    url: 'https://www.realtor.com/realestateandhomes-detail/1239-Quintero-Rd_Prescott_AZ_86305_M95321-96965',
    price: 411665,
    beds: 3, baths: 2, sqft: 1214,
    lotAcres: null, lotNote: 'Not listed — ask the builder',
    yearBuilt: 2026, yearNote: 'New build, under construction',
    listed: '2026-09-17',
    status: 'New construction',
    hoa: 'Not listed — ask',
    tax: 'New build — not yet assessed',
    water: 'Not listed', sewer: 'Not listed',
    heat: 'Gas appliances', cool: 'Not listed',
    garage: '1-car',
    elevation: 5094,
    area: 'South Ranch (Southern Collection) · north Prescott off Hwy 89',
    builder: 'Davidson Homes',
    photoCount: 20,
    photos: px('nh.rdcpix.com/5371cfed2c6fc7b7a77bdcd6caf77dcfl-', ['f1265367708', 'f3882687992', 'f1610265069', 'f3528620220', 'f3509225426', 'f512358508', 'f3310906565', 'f249287556']),
    photoWarning: 'Photos are of the builder’s model home — this house is still under construction.',
    summary: 'A new single-level build in a Davidson Homes community: open plan, quartz counters, stainless gas appliances and a covered patio. The only 3-bedroom of the four and the only one with a warranty, but also the farthest from downtown.',
    good: ['Only 3-bed of the four', 'Single level, nothing to fix', 'Builder advertising a reduced-rate promotion'],
    ask: [
      'Completion date, and whether you can walk the actual house or only the model',
      'Lot size, HOA dues and what the HOA covers',
      'What the rate promotion is worth vs. a price cut',
      'Which finishes in the model are upgrades',
      'Airport noise — Prescott Regional Airport is about 2 miles northeast',
    ],
    fire: {
      rating: 'Moderate', tone: 'mod',
      mix: { low: 49, moderate: 47, high: 4, veryHigh: 0, nonburn: 0 },
      rps: 17, flame: 'Short flames (grass)',
      text: 'Open grassland and chaparral. Grass fires here move fast but burn low and short. Upkeep across a new subdivision tends to be uniform, which helps.',
    },
    near: {
      grocery:    { name: 'Fry’s Food and Drug', where: 'Willow Creek Rd', mi: 3.6, min: 8, lat: 34.6005859, lon: -112.4584725 },
      gas:        { name: 'Circle K', where: 'Hwy 89', mi: 2.2, min: 5, lat: 34.6440986, lon: -112.432763 },
      restaurant: { name: 'Suzie’s Skyway Restaurant', where: 'at the airport', mi: 2.9, min: 7, lat: 34.6497888, lon: -112.427214 },
    },
  },
  {
    id: 'lavalley',
    short: 'Lavalley',
    addr: '918 S Lavalley Dr',
    city: 'Prescott, AZ 86303',
    lat: 34.52461, lon: -112.484579,
    url: 'https://www.realtor.com/realestateandhomes-detail/M2299853568',
    price: 375000,
    beds: 2, baths: 2, sqft: 952,
    lotAcres: 0.34,
    yearBuilt: 1961,
    listed: '2026-07-09',
    status: 'Price reduced',
    hoa: '$645/yr (≈$54/mo) · Mountain Club',
    tax: '$1,254 (2025)',
    water: 'Public', sewer: 'Septic',
    heat: 'Forced-air gas + fireplace insert', cool: 'Ceiling fans only',
    garage: 'Not listed',
    elevation: 5482,
    area: 'Mountain Club · off White Spar Rd, south of downtown',
    photoCount: 32,
    photos: px('ap.rdcpix.com/042f04b5ff0b669f391021e569ef0f23l-', ['m1931439041', 'm2815698630', 'm2981633012', 'm3073576367', 'm192964371', 'm1500915168', 'm1017036754', 'm696726674']),
    summary: 'A 1961 split-level cabin at the end of a cul-de-sac in the Mountain Club neighborhood: beamed wood ceilings, a fireplace, a deck facing the trees and a partly finished lower level for an office or workshop. About 6 minutes to Whiskey Row.',
    good: ['On the market since July with a price cut, so there’s likely room to negotiate', '6 min to downtown, 3 min to Safeway', 'Low HOA, low taxes'],
    ask: [
      'Septic: age, last pump, inspection records',
      'No A/C listed — how warm does it get in July?',
      'Split level with stairs. Is the lower level heated living space?',
      'Parking and garage aren’t listed',
      'Roof age (composition + metal)',
    ],
    fire: {
      rating: 'Low–Moderate', tone: 'low',
      mix: { low: 61, moderate: 16, high: 0, veryHigh: 0, nonburn: 22 },
      rps: 2, flame: 'Mostly low',
      text: 'The federal model rates this area mostly low hazard (juniper and piñon, gentle slope). But the listing talks about “towering trees”, and the model’s vegetation data dates from 2020, so check the trees around the house yourself.',
    },
    near: {
      grocery:    { name: 'Safeway', where: 'White Spar Rd', mi: 0.8, min: 3, lat: 34.531106, lon: -112.4748115 },
      gas:        { name: 'Shell', where: 'Grove Ave', mi: 1.8, min: 6, lat: 34.5462235, lon: -112.4755088 },
      restaurant: { name: 'Badger’s Den', where: 'White Spar Rd', mi: 0.7, min: 2, lat: 34.5210348, lon: -112.4790699 },
    },
  },
  {
    id: 'pyrite',
    short: 'Pyrite',
    addr: '1265 W Pyrite Rd',
    city: 'Prescott, AZ 86303',
    lat: 34.471425, lon: -112.48658,
    url: 'https://www.realtor.com/realestateandhomes-detail/M2554333242',
    price: 400000,
    beds: 2, baths: 2, sqft: 1056,
    lotAcres: 0.18,
    yearBuilt: 1987,
    listed: '2026-09-15',
    status: 'Under contract',
    inactive: true,
    statusNote: 'Went under contract on Sep 23, before you could see it. Left here for comparison. Your agent can ask whether the sellers are taking backup offers, since contingent deals do fall through.',
    hoa: 'None',
    tax: '$1,567',
    water: 'Shared private well', sewer: 'Septic',
    heat: 'Pellet stove, mini-split, baseboard', cool: 'Ductless mini-split',
    garage: 'Not listed',
    elevation: 5721,
    area: 'Pines south of town · borders Prescott National Forest',
    photoCount: 22,
    photos: px('ap.rdcpix.com/fb6a2a40854336f81851e059b913c56bl-', ['m2284465666', 'm2589784421', 'm3121275729', 'm3245771556', 'm164415250', 'm3073824380', 'm4145215134', 'm502119052']),
    summary: 'A two-story log cabin in the ponderosa pines, right on the edge of Prescott National Forest: 22-ft beamed ceilings, granite kitchen, big covered patio, metal roof. It’s sold furnished and has been running as an Airbnb.',
    good: ['Most “mountain” setting of the four, with trails from the door', 'Sold furnished with Airbnb history, so it could earn rent', 'No HOA, metal roof'],
    ask: [
      'Shared well: the written well agreement, recent water test, flow rate, who pays for repairs',
      'Septic: age and inspection',
      'Get a homeowners-insurance quote BEFORE making an offer (see fire risk)',
      'Airbnb booking history and whether bookings run past closing',
      'Winter road access and snow plowing (highest of the four at 5,700 ft)',
      'Heat is mainly a pellet stove. What does a winter cost?',
    ],
    fire: {
      rating: 'High', tone: 'high',
      mix: { low: 0, moderate: 18, high: 35, veryHigh: 33, nonburn: 14 },
      rps: 64, flame: 'Tall flames possible in timber',
      text: 'Of the four, this one stands out. Two-thirds of the surrounding area is rated High or Very High hazard, and it backs onto national forest. The modeled risk to a home here is roughly 4× Quintero and 30× the two downtown houses. It isn’t a dealbreaker, but check insurance availability and cost first, and ask about defensible-space clearing.',
    },
    near: {
      grocery:    { name: 'Safeway', where: 'White Spar Rd', mi: 4.8, min: 13, lat: 34.531106, lon: -112.4748115 },
      gas:        { name: 'Shell', where: 'Grove Ave', mi: 6.0, min: 16, lat: 34.5462235, lon: -112.4755088 },
      restaurant: { name: 'Badger’s Den', where: 'White Spar Rd', mi: 3.9, min: 10, lat: 34.5210348, lon: -112.4790699 },
    },
  },
  {
    id: 'idylwild',
    short: 'Idylwild',
    addr: '1524 Idylwild Rd',
    city: 'Prescott, AZ 86305',
    lat: 34.54428, lon: -112.493601,
    url: 'https://www.realtor.com/realestateandhomes-detail/M2975214796',
    price: 379900,
    beds: 1, baths: 1, sqft: 669,
    lotAcres: 1.0,
    yearBuilt: 1929,
    listed: '2026-08-25',
    status: 'Price reduced',
    hoa: 'None',
    tax: '$635',
    water: 'Public', sewer: 'Public sewer',
    heat: 'Not listed', cool: 'Ductless',
    garage: 'Not listed',
    elevation: 5484,
    area: 'West of downtown, off Gurley St',
    photoCount: 23,
    photos: px('ap.rdcpix.com/e41445f8639054d0d628093461527236l-', ['m2583064330', 'm3454896265', 'm29515000', 'm4110458168', 'm1633846937', 'm2558031086', 'm3691503521', 'm1886939678']),
    summary: 'A newly renovated 1929 cottage on a full acre a few minutes from Courthouse Square. The house is the smallest by far. Most of what you’re paying for is a downtown acre with mature trees.',
    good: ['Full acre, 4 min to Whiskey Row', 'City water and sewer, no HOA, lowest taxes', 'Freshly renovated'],
    ask: [
      '669 sq ft, 1 bed: does it actually work for you?',
      'Room to build a guest house or add on? (City of Prescott zoning)',
      'Were permits pulled for the renovation?',
      'Heating isn’t listed',
      'Age of the foundation, wiring and plumbing (1929)',
    ],
    fire: {
      rating: 'Low', tone: 'low',
      mix: { low: 0, moderate: 12, high: 2, veryHigh: 0, nonburn: 86 },
      rps: 1, flame: 'Minimal',
      text: 'Most of the surroundings are developed, so the model rates it low. A full acre of mature trees is still worth checking for clearance around the house.',
    },
    near: {
      grocery:    { name: 'Fry’s Food and Drug', where: 'Fair St', mi: 1.3, min: 4, lat: 34.5543573, lon: -112.482411 },
      gas:        { name: 'Shell', where: 'Grove Ave', mi: 1.3, min: 3, lat: 34.5462235, lon: -112.4755088 },
      restaurant: { name: 'Casa Sanchez', where: 'W Gurley St', mi: 0.2, min: 1, lat: 34.5435863, lon: -112.4925022 },
    },
  },

  // --- Added 2026-09-26 from the agent's flexmls collection (Shanen Maddox, Keller Williams).
  // Facts are the MLS sheets; days on market isn't on the sheet, so `listed` is null.
  // The Ponderosa Park pair sits ~1 min from Pyrite, so fire and errands reuse its neighbourhood;
  // their pins are placed on the street (the geocoder doesn't know these two addresses) and the
  // wildfire mix comes from the same 7x7 USFS grid method as the others.
  {
    id: 'banning',
    short: 'Banning Creek',
    addr: '375 Banning Creek Rd',
    city: 'Prescott, AZ 86303',
    lat: 34.5167074, lon: -112.4737606,
    url: LIST_URL,
    src: 'flexmls',
    mls: '1083734',
    price: 425000,
    beds: 2, baths: 2.5, sqft: 1693,
    lotAcres: 0.26,
    yearBuilt: 1982,
    listed: null,
    status: 'Active',
    hoa: '$715/yr (≈$60/mo) · Haisley Homestead',
    tax: '$1,254 (2025)',
    water: 'City', sewer: 'City',
    heat: 'Forced-air gas + wood fireplace', cool: 'Central air',
    garage: '2-car attached',
    elevation: 5569,
    area: 'Haisley Homestead · cul-de-sac off White Spar Rd',
    photoCount: 32,
    photos: ['https://cdn1.photos.sparkplatform.com/paz/20260717210218632165000000.jpg'],
    summary: 'A 1982 two-story in the pines of Haisley Homestead, in a small cul-de-sac 9 minutes from the hotel. The biggest house on the list at 1,693 sq ft, with a wrap-around deck, a wood-burning fireplace in the family room, an island kitchen, a two-car garage and central air. The neighborhood has a pool and tennis.',
    good: ['Most house of the six: 1,693 sq ft, 2-car garage, central A/C', 'City water and sewer, nothing to maintain like a well or septic', 'Lowest wildfire risk of the mountain-side homes', 'Two minutes from restaurants on White Spar'],
    ask: [
      'Two bedrooms listed, three possible: is the office a legal bedroom?',
      'Single-pane aluminum windows: what do winter heating bills look like?',
      'HOA: what the $715 covers, and whether pool and tennis access are included',
      'Roof and water-heater age (1982 house, composition roof)',
      'Deck condition (wrap-around, open) and drainage on the gentle slope',
    ],
    fire: {
      rating: 'Moderate', tone: 'mod',
      mix: { low: 0, moderate: 76, high: 0, veryHigh: 0, nonburn: 24 },
      rps: 15, flame: 'Short to moderate flames',
      text: 'Mostly moderate hazard, no high or very high pixels within about 200 m. The modeled risk to a home is about a quarter of the Ponderosa Park houses and close to Quintero’s. Pines and juniper are close, so still ask about clearance around the house.',
    },
    near: {
      grocery:    { name: 'Safeway', where: 'White Spar Rd', mi: 1.4, min: 4, lat: 34.531106, lon: -112.4748115 },
      gas:        { name: 'Shell', where: 'Grove Ave', mi: 2.6, min: 7, lat: 34.5462235, lon: -112.4755088 },
      restaurant: { name: 'Badger’s Den', where: 'White Spar Rd', mi: 0.6, min: 2, lat: 34.5210348, lon: -112.4790699 },
    },
  },
  {
    id: 'quartz',
    short: 'Quartz',
    addr: '1347 W Quartz Rd',
    city: 'Prescott, AZ 86303',
    lat: 34.4744, lon: -112.4905,
    approxPin: true,
    url: LIST_URL,
    src: 'flexmls',
    mls: '1078418',
    price: 399900,
    beds: 3, baths: 3.5, sqft: 1120,
    lotAcres: 0.2,
    yearBuilt: 1958,
    listed: null,
    status: 'Active',
    hoa: 'None (optional membership)',
    tax: '$1,352 (2025)',
    water: 'Not listed', sewer: 'Septic',
    heat: 'Mini-split', cool: 'Mini-split',
    garage: '1-car + 2-car carport',
    elevation: 5705,
    area: 'Ponderosa Park · end of a paved road, borders national forest',
    photoCount: null,
    photos: ['https://cdn2.photos.sparkplatform.com/paz/20251224010820648638000000.jpg'],
    summary: 'A 1958 ranch at the end of the road in Ponderosa Park, backing onto Prescott National Forest with a seasonal creek along one side. Main house plus an attached guest studio over the garage/workshop, each with its own mini-split, a covered 2-car carport and an oversized patio. It is sold furnished and the agent notes there are no known rental restrictions.',
    good: ['Guest studio for rent, family or an office, and no known rental restrictions', 'Sold furnished; workshop, carport and shed', 'Forest trails from the door, seasonal creek, end-of-road privacy', 'No HOA'],
    ask: [
      'Bedroom count: the MLS says 3 bedrooms, the description says 2 plus a studio. What’s the real layout, and is the studio permitted?',
      'Septic: age, last pump, and the on-site system permit (it is on file)',
      'Water: the sheet lists only the septic, not the water source. Well, private company or city, and what does it cost?',
      'Get a homeowners-insurance quote BEFORE making an offer (see fire risk)',
      'What comes with the furniture, and can the studio legally be rented?',
      'Creek: seasonal flooding history on the corner lot',
    ],
    fire: {
      rating: 'High', tone: 'high',
      mix: { low: 0, moderate: 18, high: 0, veryHigh: 12, nonburn: 70 },
      rps: 59, flame: 'Tall flames possible in timber',
      text: 'Much of the 200 m around the house reads as non-burnable, likely the road, buildings and creek, but the modeled risk to a home is about the same as Pyrite (59 vs 64) because it borders national forest with pine and very-high hazard right next door. Check insurance availability and cost first, and ask about defensible-space clearing.',
    },
    near: {
      grocery:    { name: 'Safeway', where: 'White Spar Rd', mi: 4.4, min: 11, lat: 34.531106, lon: -112.4748115 },
      gas:        { name: 'Shell', where: 'Grove Ave', mi: 5.7, min: 14, lat: 34.5462235, lon: -112.4755088 },
      restaurant: { name: 'Badger’s Den', where: 'White Spar Rd', mi: 3.6, min: 9, lat: 34.5210348, lon: -112.4790699 },
    },
  },
  {
    id: 'ponderosa',
    short: 'Ponderosa Park',
    addr: '4647 S Ponderosa Park Rd',
    city: 'Prescott, AZ 86303',
    lat: 34.4715, lon: -112.4885,
    approxPin: true,
    url: LIST_URL,
    src: 'flexmls',
    mls: '1082835',
    price: 390000,
    beds: 3, baths: 2, sqft: 1148,
    lotAcres: 0.2,
    yearBuilt: 1969,
    listed: null,
    status: 'Active',
    hoa: 'None (voluntary HOA)',
    tax: '$1,338 (2025)',
    water: 'Private water company', sewer: 'Septic',
    heat: 'Forced-air gas / propane', cool: 'Room evaporative + ceiling fans',
    garage: 'No garage · 1 carport',
    elevation: 5641,
    area: 'Ponderosa Park · just past Libby Loop, off Hwy 89 south',
    photoCount: null,
    photos: ['https://cdn1.photos.sparkplatform.com/paz/20260612232615511916000000.jpg'],
    summary: 'A flat, private 1969 ranch on a lot under ponderosa pines in Ponderosa Park, a 1950s subdivision of an 1884 homestead with a voluntary HOA, its own water company and a fire station next door. Updated flooring, paint, roof and plumbing, a walk-in closet and a deck off the primary suite. About 5 miles from downtown.',
    good: ['Level lot, single story, roof and plumbing updated', 'Fire station adjacent', 'Deck off the primary suite and a fenced private yard with shed', 'Lowest price of the three new ones'],
    ask: [
      'Private water company: rates, reliability and any shortages',
      'Septic: age, last pump, inspection records',
      'Evaporative cooler only: how warm does it get in July?',
      'No garage, one carport: is there room to add a garage?',
      'Get a homeowners-insurance quote BEFORE making an offer (see fire risk)',
      'Single-pane windows in parts of the house: which ones, and what is the plan for them?',
      'Voluntary HOA: what does membership cost and cover?',
    ],
    fire: {
      rating: 'High', tone: 'high',
      mix: { low: 0, moderate: 43, high: 16, veryHigh: 10, nonburn: 31 },
      rps: 62, flame: 'Tall flames possible in timber',
      text: 'Same neighbourhood as Pyrite and nearly the same modeled home risk (62 vs 64), with about a quarter of the 200 m around the house rated High or Very High. The adjacent fire station helps response time, but check insurance availability and cost first and ask about clearing around the pines.',
    },
    near: {
      grocery:    { name: 'Safeway', where: 'White Spar Rd', mi: 4.7, min: 12, lat: 34.531106, lon: -112.4748115 },
      gas:        { name: 'Shell', where: 'Grove Ave', mi: 5.9, min: 15, lat: 34.5462235, lon: -112.4755088 },
      restaurant: { name: 'Badger’s Den', where: 'White Spar Rd', mi: 3.9, min: 10, lat: 34.5210348, lon: -112.4790699 },
    },
  },
];

export const SCORE_CATS = [
  ['kitchen', 'Kitchen'],
  ['layout', 'Layout / flow'],
  ['condition', 'Condition'],
  ['outdoor', 'Yard & lot'],
  ['setting', 'Street & neighbors'],
  ['location', 'Location'],
  ['value', 'Value for price'],
  ['gut', 'Gut feel'],
];
